# ref: https://docs.travis-ci.com/user/languages/python
os:
  - osx
# command to install dependencies
install: 
  - brew upgrade python
  - pip3 install -r src/app/requirements.txt
  - brew cask install homebrew/cask-versions/java8
  - brew install --HEAD swagger-codegen
# command to run tests
script:
  - python3 -m invoke unittest
  - ./run_server.sh &

after_success:
  - python3 -m invoke validate

after_script:
  - cd build/app/
  - codecov 
  - killall Python