# ref: https://docs.travis-ci.com/user/languages/python
os:
  - osx
# command to install dependencies
install: 
  - brew upgrade python
  - pip3 install -r src/app/requirements.txt
  - brew cask install homebrew/cask-versions/java8
  - brew install --HEAD swagger-codegen
# command to run tests
script: python3 -m invoke unittest
after_success:
  - codecov 