# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6"
# command to install dependencies
install: "cd build/app && pip3 install -r requirements.txt"
# command to run tests
script: invoke unittest
