# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6"
# command to install dependencies
install: "pip3 install -r src/app/requirements.txt"
# command to run tests
script: invoke unittest
