# ref: https://docs.travis-ci.com/user/languages/python
os:
  - osx
jdk:
  - oraclejdk8
# command to install dependencies
install: 
  - brew upgrade python
  - pip3 install -r src/app/requirements.txt
  - brew install maven
  - brew install --HEAD swagger-codegen
# command to run tests
script: python3 -m invoke unittest
after_success:
  - codecov 