# coding: utf-8

"""
    Configuration Manager

    A simple HTTP API for managing the configuration values of a system.  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: riccardo.ancona@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration_api import ConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException

import time


API_MAX_ALLOWED_RESPONSE_TIME = 0.150 # ms

class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.configuration_api.ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_configuration(self):
        """Test case for add_configuration

        Adds a new configuration  # noqa: E501
        """         
        # create an instance of the API class
        api_instance = swagger_client.ConfigurationApi(swagger_client.ApiClient())
        cfg = swagger_client.NewConfiguration(name="GoogleSettings", value={"list" : 3}) # NewConfiguration | Configuration object to be added. Duplicates are allowed.

        start = time.clock()
        api_response = api_instance.add_configuration(cfg)
        request_time = time.clock() - start

        self.assertLessEqual(request_time, API_MAX_ALLOWED_RESPONSE_TIME, "Request completed in {}ms".format(request_time))

    def test_delete_configuration(self):
        """Test case for delete_configuration

        Deletes a Configuration  # noqa: E501
        """
        pass

    def test_find_configuration_by_name(self):
        """Test case for find_configuration_by_name

        Finds configuration by name  # noqa: E501
        """
        pass

    def test_get_configuration_by_id(self):
        """Test case for get_configuration_by_id

        Finds configuration by ID  # noqa: E501
        """
        pass

    def test_update_configuration(self):
        """Test case for update_configuration

        Updates an existing configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
